import type { Stage, WeeklyTrend } from "@/lib/schedule-data"

export const TRENDS_ZH: WeeklyTrend[] = [
  { week: "4/23–30", nightStretch: 2.8, bottleMl: 404, feedSize: 55 },
  { week: "5/1–7", nightStretch: 3.1, bottleMl: 494, feedSize: 70 },
  { week: "5/8–14", nightStretch: 2.9, bottleMl: 495, feedSize: 80 },
  { week: "5/15–21", nightStretch: 3.3, bottleMl: 517, feedSize: 90 },
  { week: "5/22–28", nightStretch: 3.9, bottleMl: 524, feedSize: 100 },
  { week: "5/29–6/6", nightStretch: 4.6, bottleMl: 449, feedSize: 105 },
]

export const STAGES_ZH: Stage[] = [
  {
    id: "s1",
    tab: "阶段 1",
    title: "建立节奏",
    dates: "6/7 – 7/5",
    age: "6–10 周（1.5–2.5 月）",
    feedsPerDay: "7–8",
    perFeed: "100–130 ml（或哺乳 15–20 分钟）",
    totalIntake: "750–900 ml/天",
    interval: "白天约每 3 小时",
    wakeWindow: "60–90 分钟",
    naps: "4–5",
    totalSleep: "15–16 小时",
    nightStretch: "5–7 小时（他已达到）",
    bedtime: "晚上 8:30–9:00",
    nightFeeds: "1–2",
    focus:
      "将入睡时间比目前的 9:00–9:45 提前约 30 分钟，并保持固定的睡前仪式。他有些夜晚已经能连续睡 6 小时以上——睡前喂饱，保护好这段长觉。",
    day: [
      { time: "7:00 AM", label: "醒来 + 第 1 餐", kind: "wake" },
      { time: "8:15 AM", label: "小睡 1", kind: "sleep" },
      { time: "9:45 AM", label: "醒来", kind: "wake" },
      { time: "10:00 AM", label: "第 2 餐", kind: "feed" },
      { time: "11:15 AM", label: "小睡 2", kind: "sleep" },
      { time: "1:00 PM", label: "醒来 + 第 3 餐", kind: "feed" },
      { time: "2:15 PM", label: "小睡 3", kind: "sleep" },
      { time: "3:45 PM", label: "醒来 + 第 4 餐", kind: "feed" },
      { time: "5:00 PM", label: "黄昏小睡", kind: "sleep" },
      { time: "6:00 PM", label: "醒来", kind: "wake" },
      { time: "7:00 PM", label: "洗澡 + 第 5 餐", kind: "feed" },
      { time: "8:30 PM", label: "入睡 — 最长连续睡眠", kind: "sleep" },
      { time: "~3:00 AM", label: "夜奶", kind: "feed" },
      { time: "~5:30 AM", label: "可选简短喂奶", kind: "feed" },
    ],
  },
  {
    id: "s2",
    tab: "阶段 2",
    title: "更少、更大的餐",
    dates: "7/6 – 8/2",
    age: "10–14 周（2.5–3.5 月）",
    feedsPerDay: "6–7",
    perFeed: "120–150 ml",
    totalIntake: "800–950 ml/天",
    interval: "3–3.5 小时",
    wakeWindow: "75–105 分钟",
    naps: "4 → 3–4",
    totalSleep: "14.5–15.5 小时",
    nightStretch: "6–8 小时",
    bedtime: "晚上 7:30–8:30",
    nightFeeds: "1",
    focus:
      "小睡开始合并为 3–4 个可预期的时段。白天喂奶间隔拉长到约 3.5 小时，让每餐量更大——这有助于夜间连续睡眠超过 7 小时，通常只需一次夜奶。",
    day: [
      { time: "7:00 AM", label: "醒来 + 第 1 餐", kind: "wake" },
      { time: "8:30 AM", label: "小睡 1", kind: "sleep" },
      { time: "10:00 AM", label: "醒来 + 第 2 餐", kind: "feed" },
      { time: "11:30 AM", label: "小睡 2", kind: "sleep" },
      { time: "1:00 PM", label: "醒来 + 第 3 餐", kind: "feed" },
      { time: "2:30 PM", label: "小睡 3", kind: "sleep" },
      { time: "4:00 PM", label: "醒来 + 第 4 餐", kind: "feed" },
      { time: "5:00 PM", label: "黄昏小睡", kind: "sleep" },
      { time: "6:00 PM", label: "醒来", kind: "wake" },
      { time: "7:00 PM", label: "洗澡 + 第 5 餐", kind: "feed" },
      { time: "7:45 PM", label: "入睡", kind: "sleep" },
      { time: "~11:00 PM", label: "可选梦中喂奶", kind: "feed" },
      { time: "~4:00 AM", label: "夜奶", kind: "feed" },
    ],
  },
  {
    id: "s3",
    tab: "阶段 3",
    title: "真正的昼夜规律",
    dates: "8/3 – 9/6",
    age: "14–19 周（3.5–4.5 月）",
    feedsPerDay: "5–6",
    perFeed: "150–180 ml",
    totalIntake: "850–1000 ml/天（上限约 960 ml）",
    interval: "3.5–4 小时",
    wakeWindow: "90–120 分钟",
    naps: "3–4",
    totalSleep: "14–15 小时",
    nightStretch: "7–9 小时（常可睡到清晨）",
    bedtime: "晚上 7:00–8:00",
    nightFeeds: "0–1",
    focus:
      "一天 3 次小睡的模式逐渐成形。留意 15–17 周可能出现的 4 月睡眠倒退——夜间短暂醒来是正常的，不代表要加回夜奶。每晚保持相同的睡前仪式，帮助他学会自己安抚。",
    day: [
      { time: "7:00 AM", label: "醒来 + 第 1 餐", kind: "wake" },
      { time: "9:00 AM", label: "小睡 1", kind: "sleep" },
      { time: "10:30 AM", label: "醒来 + 第 2 餐", kind: "feed" },
      { time: "12:30 PM", label: "小睡 2", kind: "sleep" },
      { time: "2:00 PM", label: "醒来 + 第 3 餐", kind: "feed" },
      { time: "4:00 PM", label: "小睡 3（短）", kind: "sleep" },
      { time: "5:00 PM", label: "醒来 + 第 4 餐", kind: "feed" },
      { time: "6:30 PM", label: "洗澡 / 放松", kind: "wake" },
      { time: "7:00 PM", label: "第 5 餐 + 入睡", kind: "sleep" },
      { time: "~10:30 PM", label: "可选梦中喂奶", kind: "feed" },
      { time: "~4:00 AM", label: "需要时夜奶", kind: "feed" },
    ],
  },
]

export const COMPARISON_ROWS_ZH: Array<{
  label: string
  get: (s: Stage) => string
}> = [
  { label: "月龄", get: (s) => s.age },
  { label: "日历窗口", get: (s) => s.dates },
  { label: "每日喂奶", get: (s) => s.feedsPerDay },
  { label: "每餐奶量", get: (s) => s.perFeed },
  { label: "每日总摄入", get: (s) => s.totalIntake },
  { label: "白天喂奶间隔", get: (s) => s.interval },
  { label: "清醒窗口", get: (s) => s.wakeWindow },
  { label: "每日小睡", get: (s) => s.naps },
  { label: "24 小时总睡眠", get: (s) => s.totalSleep },
  { label: "最长夜间连续睡眠", get: (s) => s.nightStretch },
  { label: "入睡时间", get: (s) => s.bedtime },
  { label: "夜奶次数", get: (s) => s.nightFeeds },
]
